[package]
name = "shift_organizer"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
anyhow = "1.0.86"
modular-bitfield = "0.11.2"